# Configuration for the data ingestion and wrangling pipeline.
# This file defines the data sources, transformations, and final output format.

ingestion:
# Ingest firm-level characteristics from the main datashare file.
- name: "firm_chars"
  path: "datashare.csv"
  format: "csv"
  to_lowercase_cols: true
  date_column: { "date": "%Y%m%d" }
  firm_id_column: "permno"

# Ingest firm-level returns.
- name: "firm_ret"
  path: "crsp_returns_dec1956_dec2021.csv"
  format: "csv"
  to_lowercase_cols: true
  date_column: { "date": "%Y-%m-%d" }
  firm_id_column: "permno"

# Ingest macroeconomic predictors.
- name: "macro"
  path: "macro_1956_2021.csv"
  format: "csv"
  to_lowercase_cols: true
  date_column: { "date": "%Y%m%d" }

# Ingest the risk-free rate.
- name: "risk_free"
  path: "risk_free_rate_1956_2021.csv"
  format: "csv"
  to_lowercase_cols: true
  date_column: { "date": "%Y%m%d" }

wrangling_pipeline:
# Impute missing values in firm characteristics.
- operation: "monthly_imputation"
  dataset: "firm_chars"
  fallback_to_zero: true
  numeric_columns:
  - "mvel1"
  - "beta"
  - "betasq"
  - "chmom"
  - "dolvol"
  - "idiovol"
  - "indmom"
  - "mom1m"
  - "mom6m"
  - "mom12m"
  - "mom36m"
  - "pricedelay"
  - "turn"
  - "absacc"
  - "acc"
  - "age"
  - "agr"
  - "bm"
  - "bm_ia"
  - "cashdebt"
  - "cashpr"
  - "cfp"
  - "cfp_ia"
  - "chatoia"
  - "chcsho"
  - "chempia"
  - "chinv"
  - "chpmia"
  - "convind"
  - "currat"
  - "depr"
  - "divi"
  - "divo"
  - "dy"
  - "egr"
  - "ep"
  - "gma"
  - "grcapx"
  - "grltnoa"
  - "herf"
  - "hire"
  - "invest"
  - "lev"
  - "lgr"
  - "mve_ia"
  - "operprof"
  - "orgcap"
  - "pchcapx_ia"
  - "pchcurrat"
  - "pchdepr"
  - "pchgm_pchsale"
  - "pchquick"
  - "pchsale_pchinvt"
  - "pchsale_pchrect"
  - "pchsale_pchxsga"
  - "pchsaleinv"
  - "pctacc"
  - "ps"
  - "quick"
  - "rd"
  - "rd_mve"
  - "rd_sale"
  - "realestate"
  - "roic"
  - "salecash"
  - "saleinv"
  - "salerec"
  - "secured"
  - "securedind"
  - "sgr"
  - "sin"
  - "sp"
  - "tang"
  - "tb"
  - "aeavol"
  - "cash"
  - "chtx"
  - "cinvest"
  - "ear"
  - "nincr"
  - "roaq"
  - "roavol"
  - "roeq"
  - "rsup"
  - "stdacc"
  - "stdcf"
  - "ms"
  - "baspread"
  - "ill"
  - "maxret"
  - "retvol"
  - "std_dolvol"
  - "std_turn"
  - "zerotrade"
  categorical_columns: [ "sic2" ]
  output_name: "imputed_firm"

# Generate dummy variables for the 'sic2' (industry) column.
# This step is placed after imputation to ensure all firms have an industry code.
- operation: "dummy_generation"
  dataset: "imputed_firm"
  column_to_dummy: "sic2"
  drop_original_col: true
  output_name: "firm_with_dummies"

# Scale firm characteristics to a range of [-1, 1].
# This now operates on the dataset that includes the new dummy variables.
- operation: "scale_to_range"
  dataset: "firm_with_dummies"
  range: { min: -1, max: 1 }
  cols_to_scale:
  - "mvel1"
  - "beta"
  - "betasq"
  - "chmom"
  - "dolvol"
  - "idiovol"
  - "indmom"
  - "mom1m"
  - "mom6m"
  - "mom12m"
  - "mom36m"
  - "pricedelay"
  - "turn"
  - "absacc"
  - "acc"
  - "age"
  - "agr"
  - "bm"
  - "bm_ia"
  - "cashdebt"
  - "cashpr"
  - "cfp"
  - "cfp_ia"
  - "chatoia"
  - "chcsho"
  - "chempia"
  - "chinv"
  - "chpmia"
  - "convind"
  - "currat"
  - "depr"
  - "divi"
  - "divo"
  - "dy"
  - "egr"
  - "ep"
  - "gma"
  - "grcapx"
  - "grltnoa"
  - "herf"
  - "hire"
  - "invest"
  - "lev"
  - "lgr"
  - "mve_ia"
  - "operprof"
  - "orgcap"
  - "pchcapx_ia"
  - "pchcurrat"
  - "pchdepr"
  - "pchgm_pchsale"
  - "pchquick"
  - "pchsale_pchinvt"
  - "pchsale_pchrect"
  - "pchsale_pchxsga"
  - "pchsaleinv"
  - "pctacc"
  - "ps"
  - "quick"
  - "rd"
  - "rd_mve"
  - "rd_sale"
  - "realestate"
  - "roic"
  - "salecash"
  - "saleinv"
  - "salerec"
  - "secured"
  - "securedind"
  - "sgr"
  - "sin"
  - "sp"
  - "tang"
  - "tb"
  - "aeavol"
  - "cash"
  - "chtx"
  - "cinvest"
  - "ear"
  - "nincr"
  - "roaq"
  - "roavol"
  - "roeq"
  - "rsup"
  - "stdacc"
  - "stdcf"
  - "ms"
  - "baspread"
  - "ill"
  - "maxret"
  - "retvol"
  - "std_dolvol"
  - "std_turn"
  - "zerotrade"
  output_name: "scaled_firm"

# Merge firm-level returns and characteristics.
# An inner join ensures we only keep observations with both return and characteristics data.
- operation: "merge"
  left_dataset: "firm_ret"
  right_dataset: "scaled_firm"
  "on": [ "date", "permno" ]
  how: "inner"
  output_name: "firm_level_data"

# Lag all macroeconomic predictors by one month.
# The firm characteristics are already lagged in the firm_ret dataset, (see README.txt from datashare.csv in the Xiu website)
# this means that if we want to predict returns at time t,
# we need firm characteristics at time t.
# So we only need to lag the macroeconomic data for consistency.
- operation: "lag"
  dataset: "macro"
  periods: 1
  columns_to_lag:
  - method: "all_except"
  - columns: [ "date" ] # Lag everything except the date column
  drop_original_cols_after_lag: true
  restore_names: true # Rename lagged columns (e.g., 'bm_lag_1') back to original names ('bm')
  drop_generated_nans: true # Remove rows where lagging created missing values
  output_name: "macro_lagged"

# Lag the risk-free rate by one month for the same reason.
- operation: "lag"
  dataset: "risk_free"
  periods: 1
  columns_to_lag:
  - method: "all_except"
  - columns: [ "date" ]
  drop_original_cols_after_lag: true
  restore_names: true
  drop_generated_nans: true
  output_name: "risk_free_lagged"

# Merge the combined firm data with macroeconomic data.
# An inner join ensures that we can compute the interaction terms only for dates where both firm and macro data are available.
- operation: "merge"
  left_dataset: "firm_level_data"
  right_dataset: "macro_lagged"
  "on": [ "date" ]
  how: "inner"
  output_name: "firm_macro_data"

# Merge with risk-free rate data.
- operation: "merge"
  left_dataset: "firm_macro_data"
  right_dataset: "risk_free_lagged"
  "on": [ "date" ]
  how: "inner"
  output_name: "merged_all"

# Create interaction features between all firm and macro variables.
# This will generate 8 (macro) * 93 (firm) = 744 interaction terms.
- operation: "create_macro_interactions"
  dataset: "merged_all"
  macro_columns:
  - "dp"
  - "ep_macro"
  - "bm_macro"
  - "ntis"
  - "tbl"
  - "tms"
  - "dfy"
  - "svar"
  firm_columns:
  - "mvel1"
  - "beta"
  - "betasq"
  - "chmom"
  - "dolvol"
  - "idiovol"
  - "indmom"
  - "mom1m"
  - "mom6m"
  - "mom12m"
  - "mom36m"
  - "pricedelay"
  - "turn"
  - "absacc"
  - "acc"
  - "age"
  - "agr"
  - "bm"
  - "bm_ia"
  - "cashdebt"
  - "cashpr"
  - "cfp"
  - "cfp_ia"
  - "chatoia"
  - "chcsho"
  - "chempia"
  - "chinv"
  - "chpmia"
  - "convind"
  - "currat"
  - "depr"
  - "divi"
  - "divo"
  - "dy"
  - "egr"
  - "ep"
  - "gma"
  - "grcapx"
  - "grltnoa"
  - "herf"
  - "hire"
  - "invest"
  - "lev"
  - "lgr"
  - "mve_ia"
  - "operprof"
  - "orgcap"
  - "pchcapx_ia"
  - "pchcurrat"
  - "pchdepr"
  - "pchgm_pchsale"
  - "pchquick"
  - "pchsale_pchinvt"
  - "pchsale_pchrect"
  - "pchsale_pchxsga"
  - "pchsaleinv"
  - "pctacc"
  - "ps"
  - "quick"
  - "rd"
  - "rd_mve"
  - "rd_sale"
  - "realestate"
  - "roic"
  - "salecash"
  - "saleinv"
  - "salerec"
  - "secured"
  - "securedind"
  - "sgr"
  - "sin"
  - "sp"
  - "tang"
  - "tb"
  - "aeavol"
  - "cash"
  - "chtx"
  - "cinvest"
  - "ear"
  - "nincr"
  - "roaq"
  - "roavol"
  - "roeq"
  - "rsup"
  - "stdacc"
  - "stdcf"
  - "ms"
  - "baspread"
  - "ill"
  - "maxret"
  - "retvol"
  - "std_dolvol"
  - "std_turn"
  - "zerotrade"
  # Note: The original 'sic2' column is dropped in the dummy_generation step,
  # so it is not available here for interactions. The new dummy columns
  # (e.g., 'sic2_10', 'sic2_11', etc.) would need to be added to this list
  # if you wish to create interactions with them.
  drop_macro_columns: true # Keep original macro columns for the baseline model
  output_name: "data_with_interactions"
  use_lazy_engine: true

export:
# Export the final, model-ready dataset to Parquet format, partitioned by year.
- dataset_name: "final_dataset_model"
  output_filename_base: "final_dataset_model" # This name is used by paper-model
  format: "parquet"
  partition_by: "year"
