# --- Tree-Based Models Configuration ---
# Contains Random Forest (RF) and Gradient Boosted Regression Trees (GBRT).
# These non-linear models are powerful and use all available features.

input_data:
  dataset_name: "final_dataset_model"
  splitted: "year"
  date_column: "date"
  id_column: "permno"
  risk_free_rate_col: "rf"

evaluation:
  implementation: "rolling window"
  train_month: 84 # 7 years
  validation_month: 24 # 2 years
  testing_month: 24 # 2 years
  step_month: 24 # The step size for the rolling window evaluation. (Usually equal to testing_month)
  metrics: [ "mse", "r2_oos" ]

models:
- name: "rf_full_tuned"
  type: "rf"
  target_column: "ret"
  features:
    method: "all_except"
    columns: [ "date", "permno", "ret", "rf" ]
  n_estimators: 300
  max_depth: [ 1, 3, 5 ]
  max_features: [ 3, 10, 30 ]
  random_state: 306
  save_prediction_results: true

# - name: "gbrt_full_tuned"
#   type: "gbrt"
#   target_column: "ret"
#   features:
#     method: "all_except"
#     columns: [ "date", "permno", "ret", "rf" ]
#   objective_function: "huber"
#   use_hist_implementation: true
#   n_estimators: [ 50, 100 ]
#   max_depth: [ 1, 2 ]
#   learning_rate: [ 0.01, 0.1 ]
#   random_state: 306
#   save_prediction_results: true
