# Configuration file for the empirical asset pricing via Machine Learning models, inspired by Gu, Kelly, and Xiu (2020).

input_data:
  dataset_name: "final_dataset_model"
  splitted: "year"
  date_column: "date"
  id_column: "permno"
  risk_free_rate_col: "rf"

evaluation:
  implementation: "rolling window"
  train_month: 216 # 18 years
  validation_month: 144 # 12 years
  testing_month: 12 # 1 year
  step_month: 12 # The step size for the rolling window evaluation. (Usually equal to testing_month)
  metrics: [ "mse", "r2_oos" ]

models:
- name: "ols3_baseline"
  type: "ols"
  target_column: "ret"
  features:
  - "mvel1"
  - "bm"
  - "mom12m"
  save_prediction_results: true

- name: "ols3_huber_adaptive"
  type: "ols"
  target_column: "ret"
  features:
  - "mvel1"
  - "bm"
  - "mom12m"
  objective_function: "huber"
  huber_epsilon_quantile: 0.999 # Adaptively set epsilon based on residuals
  save_prediction_results: true

- name: "ols_huber_adaptive"
  type: "ols"
  target_column: "ret"
  features:
    method: "all_except"
    columns: [ "date", "permno", "ret", "rf" ]
  objective_function: "huber"
  huber_epsilon_quantile: 0.999
  save_prediction_results: true

- name: "pcr_full_tuned"
  type: "pcr"
  target_column: "ret"
  features:
    method: "all_except"
    columns: [ "date", "permno", "ret", "rf" ]
  n_components: [ 20, 40, 60 ]
  # objective_function: "huber" # According to the appendix on hyperparameter tuning, this is not used.
  random_state: 306
  save_prediction_results: true

- name: "random_forest_tuned"
  type: "rf"
  target_column: "ret"
  features:
    method: "all_except"
    columns: [ "date", "permno", "ret", "rf" ]
  # The number of trees (B) in the forest is fixed according to the paper.
  n_estimators: 300
  # --- Hyperparameter Tuning ---
  # Tune the maximum depth of each tree (L).
  max_depth: [ 1, 3, 6 ]
  # Tune the number of features to consider at each split.
  # "sqrt" uses sqrt(P) features; 0.33 uses 33% of features, etc.
  max_features: [ 5, 10] # [ 0.01, 0.02, 0.03 ] # 920 * 0.01 = 9 features
  random_state: 306
  save_prediction_results: true
