# configs/paper-project.yaml
project_name: "GuKellyXiu_EmpiricalAssetPricingViaML"
version: "0.1.0"
paper_tools_version: "0.1.0"
creation_date: "2025-06-14"
description: "P.A.P.E.R project: GuKellyXiu_EmpiricalAssetPricingViaML"

components:
  data:
    config_file: "data-config.yaml"
  models:
    config_file: "models-config.yaml"
  portfolio:
    config_file: "portfolio-config.yaml"

logging:
  log_file: "logs.log"
  level: "INFO"