# configs/paper-project.yaml
project_name: "PortfolioExampleProject"
version: "0.1.0"
paper_tools_version: "0.1.0"
creation_date: "2025-06-01"
description: "P.A.P.E.R project: PortfolioExampleProject"

components:
  data:
    config_file: "data-config.yaml" # Intentionally left empty
  models:
    config_file: "models-config.yaml" # Intentionally left empty
  portfolio:
    config_file: "portfolio-config.yaml" # Core configuration for this example project

logging:
  log_file: "logs.log"
  level: "INFO"
