[tool.uv.workspace]
members = ["paper-data", "paper-model", "paper-portfolio", "paper-tools"]

# The [tool.uv.sources] section tells uv to use local workspace versions
# for these packages if they are listed as dependencies within the workspace.
# This is good for development. When you build for PyPI, the dependencies
# in individual pyproject.toml files (e.g., paper-data = "~0.1.0") will
# point to PyPI versions.
[tool.uv.sources]
paper-data = { workspace = true }
paper-model = { workspace = true }
paper-portfolio = { workspace = true }
paper-tools = { workspace = true }

[dependency-groups]
dev = [
  "pandas-stubs>=2.2.3.250308",
  "pytest>=8.3.5",
  "pytest-cov>=6.1.1",
  "ruff>=0.11.11",
  "setuptools>=80.8.0",
  "twine>=6.1.0",
]
