[tool.uv.workspace]
members = [
  "paper-data",
  "paper-model",
  "paper-portfolio",
  "paper-tools",
]

[tool.uv.sources]
paper-data      = { workspace = true }
paper-model     = { workspace = true }
paper-portfolio = { workspace = true }
paper-tools     = { workspace = true }

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "ruff>=0.11.11",
    "setuptools>=80.8.0",
]
