# configs/paper-project.yaml
project_name: "DataExampleProject"
version: "0.1.0"
paper_asset_pricing_version: "0.1.0"
creation_date: "2025-06-01"
description: "P.A.P.E.R project: DataExampleProject"

components:
  data:
    config_file: "data-config.yaml" # Core configuration for this example project
  models:
    config_file: "models-config.yaml" # Intentionally left empty
  portfolio:
    config_file: "portfolio-config.yaml" # Intentionally left empty

logging:
  log_file: "logs.log"
  level: "INFO"
