# --- Neural Network (NN) Models Configuration ---
# Contains various feed-forward neural network architectures.
# These models use all available features to capture complex non-linearities.

input_data:
  dataset_name: "final_dataset_model"
  splitted: "year"
  date_column: "date"
  id_column: "permno"
  risk_free_rate_col: "rf"

evaluation:
  implementation: "rolling window"
  train_month: 120
  validation_month: 24
  testing_month: 12
  step_month: 12
  metrics: [ "mse", "r2_oos" ]

models:
- name: "nn1_tuned"
  type: "nn"
  target_column: "ret"
  features:
    method: "all_except"
    columns: [ "date", "permno", "ret", "rf", "sic2" ]
  hidden_layer_sizes: [ 32 ]
  alpha: 0.0001 # [ 0.00001, 0.0001 ]
  learning_rate: 0.01 # [ 0.001, 0.01 ]
  batch_size: 10000
  epochs: 100
  patience: 5
  n_ensembles: 5
  random_state: 306
  device: "cuda"
  num_workers: 4
  save_prediction_results: true

# - name: "nn3_tuned"
#   type: "nn"
#   target_column: "ret"
#   features:
#     method: "all_except"
#     columns: [ "date", "permno", "ret", "rf", "sic2" ]
#   hidden_layer_sizes: [ 32, 16, 8 ]
#   alpha: [ 0.00001, 0.0001 ]
#   learning_rate: [ 0.001, 0.01 ]
#   batch_size: 10000
#   epochs: 100
#   patience: 5
#   n_ensembles: 10
#   random_state: 306
#   device: "cpu"
#   num_workers: 4
#   save_prediction_results: true
