# --- OLS Models Configuration ---
# Contains simple Ordinary Least Squares models with explicit feature lists.
# Ideal for establishing a baseline performance (e.g., Fama-French 3-factor).

input_data:
  dataset_name: "final_dataset_model"
  splitted: "year"
  date_column: "date"
  id_column: "permno"
  risk_free_rate_col: "rf"

evaluation:
  implementation: "rolling window"
  train_month: 84 # 7 years
  validation_month: 24 # 2 years
  testing_month: 24 # 2 years
  step_month: 24 # The step size for the rolling window evaluation. (Usually equal to testing_month)
  metrics: [ "mse", "r2_oos" ]

models:
- name: "ols_baseline"
  type: "ols"
  target_column: "ret"
  features:
  - "mvel1"
  - "bm"
  - "mom12m"
  save_prediction_results: true

- name: "ols_huber_adaptive"
  type: "ols"
  target_column: "ret"
  features:
  - "mvel1"
  - "bm"
  - "mom12m"
  objective_function: "huber"
  huber_epsilon_quantile: 0.999 # Adaptively set epsilon based on residuals
  save_prediction_results: true
