input_data:
  prediction_model_names:
  - "ols_huber_adaptive"
  - "elastic_net_model"
  - "pcr_tuned_model"
  - "pls_tuned_model"
  - "glm_tuned_model"
  - "random_forest_tuned"
  - "gbrt_huber_tuned"
  - "nn1_model"
  processed_dataset_name: "final_dataset_model"
  date_column: "date"
  id_column: "permno"
  risk_free_rate_col: "rf"
  value_weight_col: "mvel1" # Corrected to market value, as 'bm' is book-to-market

strategies:
- name: "EQ90"
  weighting_scheme: "equal"
  long_quantiles: [ 0.9, 1.0 ]
  short_quantiles: [ 0.0, 0.1 ]

- name: "VAL90"
  weighting_scheme: "value"
  long_quantiles: [ 0.9, 1.0 ]
  short_quantiles: [ 0.0, 0.1 ]

- name: "EQ95"
  weighting_scheme: "equal"
  long_quantiles: [ 0.90, 0.95 ]
  short_quantiles: [ 0.05, 0.10 ]

- name: "VAL95"
  weighting_scheme: "value"
  long_quantiles: [ 0.90, 0.95 ]
  short_quantiles: [ 0.05, 0.10 ]

metrics:
- "sharpe_ratio"
- "expected_shortfall"
- "cumulative_return"
