data:
  path: "data/expanded_2002_2021.parquet"
  target_column: "ret_firm"
  id_columns: ["permno", "date"]

model:
  name: "OLS"
  params:
    fit_intercept: True

evaluation:
  # Parameters for Rolling-Forward Validation
  train_years: 7
  val_years: 2   # Set to 0 if no explicit validation set is needed per fold for hyperparam tuning
  test_years: 2
  roll_years: 2  # How many years to slide the window forward