name: CI & Test Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-and-coverage:
    name: Run Tests and Upload Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install testing tools
          pip install pytest pytest-cov
          # Install all workspace packages in editable mode
          # This ensures that pytest-cov can find and measure them
          pip install -e ./paper-data
          pip install -e ./paper-model
          pip install -e ./paper-portfolio
          pip install -e ./paper-asset-pricing

      - name: Run tests with coverage
        run: |
          pytest \
            --cov=paper-data \
            --cov=paper-model \
            --cov=paper-portfolio \
            --cov=paper-asset-pricing \
            --cov-branch \
            --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
